/**
 * Canonical node type labels and descriptions.
 * Single source of truth — imported by Toolbar, SearchPalette, QuickNodeMenu, graphDocs.
 */

/** Full human-readable labels for node types (used in search, docs, descriptions) */
export const TYPE_LABELS: Record<string, string> = {
  source: 'Source', transform: 'Transform', filter: 'Filter', output: 'Output',
  math: 'Math', clamp: 'Clamp', remap: 'Remap',
  sin: 'Sin', cos: 'Cos', tan: 'Tan', abs: 'Abs',
  floor: 'Floor', ceil: 'Ceil', round: 'Round', log: 'Log', sqrt: 'Sqrt',
  lerp: 'Lerp',
  concat: 'Concat', template: 'Template',
  'string-length': 'String Length', 'string-trim': 'String Trim',
  'string-split': 'String Split', 'string-case': 'String Case',
  'parse-number': 'Parse Number',
  compare: 'Compare', switch: 'Switch',
  and: 'And', or: 'Or', not: 'Not', xor: 'Xor',
  'compose-vec3': 'Compose Vec3', 'decompose-vec3': 'Decompose Vec3',
  'dot-product': 'Dot Product', 'cross-product': 'Cross Product',
  'normalize-vec3': 'Normalize Vec3', 'vec3-length': 'Vec3 Length',
  mean: 'Mean', median: 'Median', stddev: 'Std Dev',
  'min-array': 'Min Array', 'max-array': 'Max Array',
  note: 'Note', reroute: 'Reroute', random: 'Random', display: 'Display', 'image-preview': 'Image Preview',
  timer: 'Timer', 'http-fetch': 'HTTP Fetch',
  'color-picker': 'Color Picker', 'color-mix': 'Color Mix',
  'hsl-to-rgb': 'HSL to RGB', 'rgb-to-hsl': 'RGB to HSL',
  'create-array': 'Create Array', 'get-element': 'Get Element', 'set-element': 'Set Element',
  'array-length': 'Array Length', 'array-push': 'Array Push',
  'array-filter': 'Array Filter', 'array-map': 'Array Map', 'array-reduce': 'Array Reduce',
  'create-object': 'Create Object', 'get-property': 'Get Property', 'set-property': 'Set Property',
  'object-keys': 'Object Keys', 'object-values': 'Object Values', 'merge-objects': 'Merge Objects',
  'string-concat': 'String Concat', 'string-replace': 'String Replace',
  'string-includes': 'String Includes', 'string-template': 'String Template',
  'if-gate': 'If Gate', select: 'Select',
  'get-var': 'Get Variable', 'set-var': 'Set Variable',
  'json-parse': 'JSON Parse', 'json-stringify': 'JSON Stringify',
  'base64-encode': 'Base64 Encode', 'base64-decode': 'Base64 Decode',
  'uri-encode': 'URI Encode', 'uri-decode': 'URI Decode',
  'array-slice': 'Array Slice', 'array-find': 'Array Find', 'array-sort': 'Array Sort',
  'array-reverse': 'Array Reverse', 'array-flatten': 'Array Flatten',
  'array-zip': 'Array Zip', 'array-unique': 'Array Unique',
  'get-timestamp': 'Get Timestamp', 'format-date': 'Format Date', 'parse-date': 'Parse Date',
  custom: 'Custom', subgraph: 'Subgraph',
  'subgraph-input': 'Input', 'subgraph-output': 'Output',
};

/** Abbreviated labels for compact UI (toolbar buttons, quick menus) */
export const TYPE_LABELS_SHORT: Record<string, string> = {
  'string-length': 'Str Length', 'string-trim': 'Str Trim',
  'string-split': 'Str Split', 'string-case': 'Str Case',
  'parse-number': 'Parse Num',
  'compose-vec3': 'Comp Vec3', 'decompose-vec3': 'Decomp Vec3',
  'dot-product': 'Dot Prod', 'cross-product': 'Cross Prod',
  'normalize-vec3': 'Norm Vec3', 'vec3-length': 'Vec3 Len',
  'min-array': 'Min Arr', 'max-array': 'Max Arr',
  'color-picker': 'Color Pick', 'color-mix': 'Color Mix',
  'hsl-to-rgb': 'HSL→RGB', 'rgb-to-hsl': 'RGB→HSL',
  'http-fetch': 'HTTP Fetch',
  'create-array': 'Array', 'get-element': 'Get Elem', 'set-element': 'Set Elem',
  'array-length': 'Arr Len', 'array-push': 'Arr Push',
  'array-filter': 'Arr Filter', 'array-map': 'Arr Map', 'array-reduce': 'Arr Reduce',
  'create-object': 'Obj Create', 'get-property': 'Get Prop', 'set-property': 'Set Prop',
  'object-keys': 'Obj Keys', 'object-values': 'Obj Values', 'merge-objects': 'Merge Obj',
  'string-concat': 'Str Concat', 'string-replace': 'Str Replace',
  'string-includes': 'Str Includes', 'string-template': 'Str Template',
  'get-var': 'Get Var', 'set-var': 'Set Var',
  'json-parse': 'JSON Parse', 'json-stringify': 'JSON Str',
  'base64-encode': 'B64 Encode', 'base64-decode': 'B64 Decode',
  'uri-encode': 'URI Encode', 'uri-decode': 'URI Decode',
  'array-slice': 'Arr Slice', 'array-find': 'Arr Find', 'array-sort': 'Arr Sort',
  'array-reverse': 'Arr Rev', 'array-flatten': 'Arr Flat',
  'array-zip': 'Arr Zip', 'array-unique': 'Arr Unique',
  'get-timestamp': 'Timestamp', 'format-date': 'Fmt Date', 'parse-date': 'Parse Date',
  'subgraph-input': 'Input', 'subgraph-output': 'Output',
  stddev: 'Std Dev',
};

/** Get the display label for a node type: uses short label if available, else full label, else type key */
export function getNodeLabel(type: string, short = false): string {
  if (short) return TYPE_LABELS_SHORT[type] ?? TYPE_LABELS[type] ?? type;
  return TYPE_LABELS[type] ?? type;
}

/** Short descriptions for node types (tooltips, search results, docs) */
export const TYPE_DESCRIPTIONS: Record<string, string> = {
  source: 'Numeric value input',
  transform: 'Multiply and offset a value',
  filter: 'Threshold gate for values',
  output: 'Display result value',
  math: 'Add, subtract, multiply, divide',
  clamp: 'Constrain value to a range',
  remap: 'Map value from one range to another',
  sin: 'Sine trigonometric function',
  cos: 'Cosine trigonometric function',
  tan: 'Tangent trigonometric function',
  abs: 'Absolute value',
  floor: 'Round down to integer',
  ceil: 'Round up to integer',
  round: 'Round to nearest integer',
  log: 'Natural logarithm',
  sqrt: 'Square root',
  lerp: 'Linear interpolation between two values',
  concat: 'Join strings together',
  template: 'String template with placeholders',
  'string-length': 'Count characters in a string',
  'string-trim': 'Remove leading/trailing whitespace',
  'string-split': 'Split string by delimiter',
  'string-case': 'Convert string to upper/lower case',
  'parse-number': 'Convert string to number',
  compare: 'Compare two values (>, <, =, etc.)',
  switch: 'Match value against cases',
  and: 'Boolean AND logic',
  or: 'Boolean OR logic',
  not: 'Boolean NOT (invert)',
  xor: 'Boolean exclusive OR',
  'compose-vec3': 'Create a 3D vector from x, y, z',
  'decompose-vec3': 'Extract x, y, z from a 3D vector',
  'dot-product': 'Dot product of two vectors',
  'cross-product': 'Cross product of two vectors',
  'normalize-vec3': 'Normalize vector to unit length',
  'vec3-length': 'Length/magnitude of a vector',
  mean: 'Average of an array of numbers',
  median: 'Middle value of a sorted array',
  stddev: 'Standard deviation of an array',
  'min-array': 'Minimum value in an array',
  'max-array': 'Maximum value in an array',
  note: 'Text note (no processing)',
  reroute: 'Pass-through connection point',
  random: 'Generate a random number',
  display: 'Show a value as text',
  'image-preview': 'Show an image from a URL in 3D',
  timer: 'Periodic tick output',
  'http-fetch': 'Fetch data from a URL',
  'color-picker': 'Pick a color (hex output)',
  'color-mix': 'Blend two colors together',
  'hsl-to-rgb': 'Convert HSL to RGB color',
  'rgb-to-hsl': 'Convert RGB to HSL color',
  'create-array': 'Build an array from inputs',
  'get-element': 'Get element at index',
  'set-element': 'Set element at index',
  'array-length': 'Count array elements',
  'array-push': 'Append value to array',
  'array-filter': 'Filter array by expression',
  'array-map': 'Transform array elements',
  'array-reduce': 'Reduce array to single value',
  'create-object': 'Build an object from key-value pairs',
  'get-property': 'Read a property from an object',
  'set-property': 'Set a property on an object',
  'object-keys': 'Get array of object keys',
  'object-values': 'Get array of object values',
  'merge-objects': 'Merge two objects together',
  'string-concat': 'Concatenate two strings',
  'string-replace': 'Find and replace in a string',
  'string-includes': 'Check if string contains substring',
  'string-template': 'Format string with placeholders',
  'if-gate': 'Conditional value gate',
  select: 'Select from inputs by index',
  'get-var': 'Read a graph variable',
  'set-var': 'Write a graph variable',
  custom: 'Custom JavaScript expression',
  subgraph: 'Reusable sub-graph',
  'subgraph-input': 'Input port for a subgraph',
  'subgraph-output': 'Output port for a subgraph',
  'json-parse': 'Parse JSON string to object',
  'json-stringify': 'Convert value to JSON string',
  'base64-encode': 'Encode string to Base64',
  'base64-decode': 'Decode Base64 to string',
  'uri-encode': 'URL-encode a string',
  'uri-decode': 'URL-decode a string',
  'array-slice': 'Extract a portion of an array',
  'array-find': 'Find first matching element',
  'array-sort': 'Sort array elements',
  'array-reverse': 'Reverse array order',
  'array-flatten': 'Flatten nested arrays',
  'array-zip': 'Zip two arrays together',
  'array-unique': 'Remove duplicate elements',
  'get-timestamp': 'Current Unix timestamp',
  'format-date': 'Format timestamp as date string',
  'parse-date': 'Parse date string to timestamp',
};

/** Color hex by config color key — uses CSS variable names for theme awareness */
export const COLOR_HEX: Record<string, string> = {
  teal: 'var(--teal)',
  orange: 'var(--orange)',
  coral: 'var(--coral)',
  'teal-coral': 'var(--purple)',
};
